# Generated by Django 5.0.1 on 2024-01-17 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail_chain", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retailchain",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="retailchain",
            name="products",
        ),
        migrations.AddField(
            model_name="contacts",
            name="owner",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="retail_chain.retailchain",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="supplier",
            field=models.ManyToManyField(
                related_name="products", to="retail_chain.retailchain"
            ),
        ),
    ]
