# Generated by Django 5.0.1 on 2024-01-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retail_chain", "0002_remove_retailchain_contacts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to="retail_chain.retailchain",
                verbose_name="относящиеся к",
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="supplier",
            field=models.ManyToManyField(
                related_name="products",
                to="retail_chain.retailchain",
                verbose_name="поставщик",
            ),
        ),
    ]
